config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :publications, only: [:index, :show]
  namespace :admin do
    resources :publications
  end
end

app/models/publication.rb
class Publication < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/publications_controller.rb
class Admin::PublicationsController < AdminController
  AdminController
  before_filter :find_publication, only: [:show, :edit, :update, :destroy]

  def index
    @publications = Publication.all
  end

  def show; end

  def new
    @publication = Publication.new
  end

  def create
    @publication = Publication.new(publication_params)

    if @publication.save
      redirect_to
      admin_publication_path(@publication)
    else
      render :new, alert: "Something went wrong."
    end
  end

  def edit; end

  def update
    if @publication.update(publication_params)
      redirect_to
      admin_publication_path(@publication)
    else
      render :edit, alert: "Something went wrong."
    end
  end

  def destroy
    @publication.destroy
    redirect_to admin_publications_path, alert: "Successfully deleted publication"
  end

  private
  def find_publication
    @publication = Publication.find(params[:id])
  end

  def publication_params
    params.require(:publication).permit(:title, :description, :file_url)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :check_for_admin
  def check_for_admin
    if current_user.nil? || !current_user.is_admin?
      redirect_to root_path, alert: "You must be an admin to access this path."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  def index
    @publications = Publication.all
  end

  def show
    @publication = Publication.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/publications/edit.html.erb
<h3>Edit <%= @publication.title %></h3>

<%= form_for @publication, url: admin_publication_path(@publication) do |f| %>
  <div class="form-group">
    <label>Title</label>
    <%=f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>Description</label>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>File URL</label>
    <%= f.text_field :file_url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Publication", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/publications/index.html.erb
<h2>Publications</h2>
<div>
  <%= link_to "New publication", new_admin_publication_path, class: 'btn btn-primary' %>
</div>

<% @publications.each do |publication| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= publication.title %></h3>
    </div>
    <div class="panel-body">
      <p><%= publication.description %></p>
      <p><%= publication.file_url %></p>
    </div>
    <div class="panel-footer">
      <%= link_to "View more details", admin_publication_path(publication), class:"btn btn-default" %>
      <%= link_to "Edit", edit_admin_publication_path(publication), class:"btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/admin/publications/new.html.erb
<h3>New Publication</h3>

<%= form_for @publication, url: admin_publications_path do |f| %>
  <div class="form-group">
    <label>Title</label>
    <%=f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>Description</label>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>File URL</label>
    <%= f.text_field :file_url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Publication", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/publications/show.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @publication.title %></h3>
    </div>
    <div class="panel-body">
      <p><%= @publication.description %></p>
      <p><%= @publication.file_url %></p>
    </div>
  </div>

app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Subscription App</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li>
              <a href='#'>Signed in as <%= current_user.email %></a>
            </li>
            <li>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
             <li>
               <%= link_to "Sign In", new_user_session_path %>
             </li>
             <li>
               <%= link_to "Sign Up", new_user_registration_path %>
             </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/index.html.erb
<h1>Home index</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SubscriptionApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
  <%= render 'nav' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/publications/index.html.erb
<h2>Publications</h2>


<% @publications.each do |publication| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= publication.title %></h3>
    </div>
    <div class="panel-body">
      <p><%= publication.description %></p>
      <p><%= publication.file_url %></p>
    </div>
    <div class="panel-footer">
      <%= link_to "View more details", publication_path(publication), class:"btn btn-default" %>
    </div>
  </div>
<% end %>